In [ ]:
# Import Library of Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
import numpy as np
import matplotlib.pyplot as plt

#assigning predictor and target variables
x= np.array([[-3,7],[1,5], [1,2], [-2,0], [2,3], [-4,0], [-1,1], [1,1], [-2,2], [2,7], [-4,1], [-2,7]])
x_new=x[:,0].reshape(len(x),1)
Y = np.array([3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 4])
Y_new=Y.reshape(len(Y),1)
plt.scatter(x_new,Y)
plt.show()
#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using the training sets 
model.fit(x, Y)


#Predict Output 
predicted= model.predict([990,90])

In [6]:

predicted

array([4])

In [7]:
Y.shape

(12,)

In [8]:
model.get_params([1])

{'priors': None}

In [9]:
x,Y


(array([[-3,  7],
        [ 1,  5],
        [ 1,  2],
        [-2,  0],
        [ 2,  3],
        [-4,  0],
        [-1,  1],
        [ 1,  1],
        [-2,  2],
        [ 2,  7],
        [-4,  1],
        [-2,  7]]), array([3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 4]))

In [14]:
x[:,0].mean(),x[:,0].std(),x[:,1].mean(),x[:,1].std()

(-0.91666666666666663, 2.1392496088322392, 3.0, 2.6457513110645907)

In [18]:
import math
def calculateProbability(x, mean, stdev):
	exponent = math.exp(-(math.pow(x-mean,2)/(2*math.pow(stdev,2))))
	return (1 / (math.sqrt(2*math.pi) * stdev)) * exponent

In [29]:
calculateProbability(0.0000009,-0.91666,2.1392)

0.17013222845739023

0.4020260290908482

In [30]:
x

array([[-3,  7],
       [ 1,  5],
       [ 1,  2],
       [-2,  0],
       [ 2,  3],
       [-4,  0],
       [-1,  1],
       [ 1,  1],
       [-2,  2],
       [ 2,  7],
       [-4,  1],
       [-2,  7]])

In [32]:
Y

array([3, 3, 3, 3, 4, 3, 3, 4, 3, 4, 4, 4])

In [33]:
def separateByClass(dataset):
	separated = {}
	for i in range(len(dataset)):
		vector = dataset[i]
		if (vector[-1] not in separated):
			separated[vector[-1]] = []
		separated[vector[-1]].append(vector)
	return separated


In [47]:
a=[[1,2],[3,4]]

a=np.array(a)

In [48]:
a

array([[1, 2],
       [3, 4]])

In [49]:
b=a

In [50]:
b

array([[1, 2],
       [3, 4]])

In [53]:
b=b[:,1].reshape(2,1)

In [54]:
b

array([[2],
       [4]])

In [56]:
a=a.reshape(2,2)

In [57]:
a.shape

(2, 2)

In [59]:
np.hstack((a,b))

array([[1, 2, 2],
       [3, 4, 4]])

In [60]:
x.shape

(12, 2)

In [61]:
Y.shape

(12,)

In [62]:
y=Y.reshape(12,1)

In [67]:
dataset=np.hstack((x,y))

In [72]:
dictt=separateByClass(dataset)

In [73]:
dictt[3]

[array([-3,  7,  3]),
 array([1, 5, 3]),
 array([1, 2, 3]),
 array([-2,  0,  3]),
 array([-4,  0,  3]),
 array([-1,  1,  3]),
 array([-2,  2,  3])]

In [92]:
def mean(numbers):
	return sum(numbers)/float(len(numbers))

def stdev(numbers):
	avg = mean(numbers)
	variance = sum([pow(x-avg,2) for x in numbers])/float(len(numbers)-1)
	return math.sqrt(variance)

def summarize(dataset):
	summaries = [(mean(attribute), stdev(attribute)) for attribute in zip(*dataset)]
	del summaries[-1]
	return summaries
def summarizeByClass(dataset):
	separated = separateByClass(dataset)
	summaries = {}
	for classValue, instances in separated.items():
		summaries[classValue] = summarize(instances)
	return summaries


{3: [(-1.4285714285714286, 1.902379462422684),
  (2.4285714285714284, 2.63673679998231)],
 4: [(-0.20000000000000001, 2.6832815729997477),
  (3.7999999999999998, 3.03315017762062)]}

In [126]:
def calculateClassProbabilities(summaries, inputVector):
	probabilities = {}
	for classValue, classSummaries in summaries.items():
		probabilities[classValue] = 1
		for i in range(len(classSummaries)):
            
			mean, stdev = classSummaries[i]
			print(mean,stdev)
			x = inputVector[i]
			probabilities[classValue] *= calculateProbability(x, mean, stdev)
	print(probabilities)            
	return probabilities
			
def predict(summaries, inputVector):
	probabilities = calculateClassProbabilities(summaries, inputVector)
	bestLabel, bestProb = None, -1
	for classValue, probability in probabilities.items():
		if bestLabel is None or probability > bestProb:
			bestProb = probability
			bestLabel = classValue
	return bestLabel


In [127]:
calculateClassProbabilities(summarizeByClass(dataset), [1,2])

-1.42857142857 1.902379462422684
2.42857142857 2.63673679998231
-0.2 2.6832815729997477
3.8 3.03315017762062
{3: 0.01386228234958858, 4: 0.014837370040045645}


{3: 0.01386228234958858, 4: 0.014837370040045645}

In [129]:
predict(summarizeByClass(dataset),[1,2])

-1.42857142857 1.902379462422684
2.42857142857 2.63673679998231
-0.2 2.6832815729997477
3.8 3.03315017762062
{3: 0.01386228234958858, 4: 0.014837370040045645}


4